name: enshan
on:
  workflow_dispatch:
  # push:
  schedule:
    - cron: 40 16 * * *
jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 50
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm run install
      - run: npm run enshan
        env:
          ENSHAN_COOKIE: ${{ secrets.ENSHAN_COOKIE }}
          DINGTALK_WEBHOOK: ${{ secrets.DINGTALK_WEBHOOK }}
          DINGTALK_SECRET: ${{ secrets.DINGTALK_SECRET }}